---
title: "01_data preprocessing"
author: "Fabienne Kock"
date: "8 6 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
if necessary:
```{r}
install.packages("brms")
```
packages
```{r}
library(effsize)
library(brms)
library(tidyverse)
```
1. read in the data
```{r}
data <- read_csv("C:\\Users\\User\\Documents\\Semester4\\Psychology Lab\\XPLabFinal\\data\\01 pilot\\S4a_data_clean.csv")
data
```

2 filter out necessary data
```{r}
trust <- filter(data, question == "Vertrauenswürdigkeit")
dom <- filter(data, question == "Dominanz")
d_t <- rbind(trust,dom)
trust
dom
d_t
regression_data$Dom <- dom$response
regression_data$Trust <- trust$response
regression_data

```
3. visualize with boxplots
```{r}
ggplot(d_t, aes(x= question, y= response, fill = question)) + 
  geom_boxplot()

```

4. median, mean and standard deviation
```{r}
dplyr::group_by(d_t, question) %>%
  dplyr::summarise(
    median = median(response, na.rm = TRUE),
    mean = mean(response, na.rm = TRUE),
    sd = sd(response, na.rm = TRUE)
  )


```

5. paired sample t-test
5.1shapoiro test
```{r}
shapiro.test(trust$response)
shapiro.test(dom$response)
```
5.2 F-test
```{r}
var.test(response ~ question, data = d_t)
```
5.3 t-test ( applicable if the p for the shapiro and the f_test are abpove the significance level alpha of 0.05)
```{r}
t.test(trust$response,dom$response,paired=TRUE)

```

6.cohens d
```{r}
cohen.d(trust$response, dom$response, paired = TRUE)

```
```{r}
analyse <- brm(response ~ question$VertrauenswÜrdigkeit + question$Dominanz)
```



