---
title: "02 data_analysis"
author: "Fabienne Kock"
date: "10 6 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

packages
```{r}
library(tidyverse)
library(effsize)
library(dplyr)
library(readr)
library(tidyr)
```
## 1. read in the data
```{r}
exp_data <- read_csv("C:\\Users\\User\\Documents\\Semester4\\Psychology Lab\\XPLabFinal\\data\\03 paper\\clean\\S4b_exp_data.csv")
subj_data <- read_csv( "C:\\Users\\User\\Documents\\Semester4\\Psychology Lab\\XPLabFinal\\data\\03 paper\\clean\\S4b_subject_data.csv")
exp_data
```

## 2 Pearson correlation between each participants rating of the upright and the inverted faces
### 2.0 split data in inverted and transposed
```{r}
upright <- select(exp_data, ID, ends_with("upright"))
inverted <- select(exp_data, ID, ends_with("inverted"))
```
### 2.1 transpose data
```{r}
upright_t <- t(upright)
inverted_t <- t(inverted)
```

```{r}
colnames(df.upright_t) <- df.upright_t[1,]
df.upright_t <- df.upright_t[-1,]
colnames(df.inverted_t) <- df.inverted_t[1,]
df.inverted_t <- df.inverted_t[-1,]

```


### 2.2 calculate Pearson correlation
```{r}
pearson <- c()
col <- 1
while(col <= ncol(upright_t)){
  name <- colnames(df.upright_t)[col]
  inv <- as.double(df.inverted_t[,name])
  up <- as.double(df.upright_t[,name])
  p_val <- cor.test(up,inv,method = "pearson")
  pearson <- c(pearson, toString(p_val)) 
  col <- col+ 1
}
exp_data$pearson <- pearson
```
```{r} how it should look like if one does not coerce it into a string
name <- colnames(df.upright_t)[1]
inv <- as.double(df.inverted_t[,name])
up <- as.double(df.upright_t[,name])
p_val <- cor.test(up,inv,method = "pearson")
p_val
```


```{r}
head(exp_data$pearson)

```
## 3. one way ANova 