---
title: "01 data_preprocessing-pilot"
author: "Fabienne Kock"
date: "22 7 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## packages
```{r}
library(tidyverse)
library(effsize)
library(readr)
library(tidyr)
library(DescTools)
library(Rmisc)
library(dplyr)
library(checkmate)
```


## 1. read in the data
```{r}
data <- read_csv("C:\\Users\\User\\Documents\\Semester4\\Psychology Lab\\XPLabFinal\\data\\02 main\\raw\\results_2019-22-07.csv")
data
```
## filter for trait-test and picture-test and filter out the personal subject data
```{r}
trait_data <- filter(data, trial_name == 'rate_personality')
trait_data <- select(trait_data, trial_number, response, RT, question, timeSpent, submission_id)
trait_data
write_csv(trait_data, "C:\\Users\\User\\Documents\\Semester4\\Psychology Lab\\XPLabFinal\\data\\02 main\\clean\\S4a_data_test.csv")
```
```{r}
pic_data <-filter(data, trial_name == 'rate_face')
pic_data <- select(pic_data, response, RT, picture, pictureFormat, color, category, timeSpent, submission_id)
pic_data
```

### clean the subject data to only include every submission_id once
```{r}

subj_data <- select(data, category, age, gender, languages, submission_id)
subj_data <- filter(subj_data, complete.cases(category))
subj_data <- subj_data[!duplicated(subj_data$submission_id), ]
subj_data
```
## cleaning up ouliers in the trait-data and pic_data

```{r}
#creates a list with all subject_ids
all_subjects_id<- unique(pic_data["submission_id"])
stop <- lengths(all_subjects_id, use.names = FALSE)
#creates a counter 
counter_id = 1
all_same_data <- vector("list", stop)
muster_data <- vector("list", stop)
rt_data <- vector("list", stop)
#starts a while loop do go through all subjects
while(counter_id <= stop){
  
id_num <- all_subjects_id[[counter_id,1]]
#filters all the data of one subject
id_data_pic <- filter(pic_data, submission_id == id_num )
id_data_trait <-  filter(trait_data, submission_id == id_num )
#filters the rating of one subject
ratings_pic <- id_data_pic["response"]
ratings_trait <- id_data_trait["response"]
#filters the respones time of an subject and the standard dividion of the respones time of all subejects 
rt_pic <- id_data_pic["RT"]
rt_trait <- id_data_trait["RT"]
rt_all_pic <- sd(pic_data[["RT"]])
rt_all_trait <- sd(trait_data[["RT"]])
#checks if the answer is allways the same
if(lengths(unique(ratings_pic))== 1 | lengths(unique(ratings_trait))== 1) {
  
    pic_data <- filter(pic_data, submission_id !=     id_num)
    trait_data <- filter(trait_data, submission_id == id_num )
    all_same_data[[counter_id]] <- id_num 
    }
    
 #filters the muster 1,2,3,4,5,6,7
  i = 1
  muster = 1
  counter = 0
  del = 0
  while (i <= lengths(ratings_pic)){
    if (muster == ratings_pic[i,1]){
      counter = counter +1
    }
    muster = muster +1
    if (muster == 7){
      muster = 1
    if (counter == 7){
        del = del +1
        counter = 0
      }
    }
    i = i+1
  }
  if (del >= 4){
    muster_data[[counter_id]] <- id_num
    pic_data <- filter(pic_data, submission_id != id_num)
     trait_data <- filter(trait_data, submission_id == id_num )
  }
  
#filters for the respones time 
if((colMeans(rt_pic) < 
    (rt_all_pic - (rt_all_pic*3 - rt_all_pic)))| 
    colMeans(rt_pic) > rt_all_pic*3)
  
{
  
   rt_data[[counter_id]] <- id_num
   pic_data <- filter(pic_data, submission_id != id_num)
    trait_data <- filter(trait_data, submission_id == id_num )
    
  }
  
  #gets the next subject
  counter_id = counter_id + 1
  counter_id = asInt(counter_id)
}
```

### count the outliers


```{r}
num_out_same <- length(unique(all_same_data)) -1
num_out_muster <- length(unique(muster_data)) -1
num_out_rt <- lengths(unique(rt_data)) -1
```

```{r}
trait_data
```

## create files with clean data for the analysis
```{r}
write_csv(subj_data, "C:\\Users\\User\\Documents\\Semester4\\Psychology Lab\\XPLabFinal\\data\\02 main\\clean\\Subject_data.csv")
write_csv(trait_data, "C:\\Users\\User\\Documents\\Semester4\\Psychology Lab\\XPLabFinal\\data\\02 main\\clean\\S4a_data.csv")
write_csv(pic_data, "C:\\Users\\User\\Documents\\Semester4\\Psychology Lab\\XPLabFinal\\data\\02 main\\clean\\S1_data.csv")
```


