---
title: "02 data_analysis"
author: "Fabienne Kock"
date: "13 6 2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


packages
```{r}
library(tidyverse)
library(readr)
library(brms)
```

## 1. read in the data
```{r}
data <- read_csv("C:\\Users\\User\\Documents\\Semester4\\Psychology Lab\\XPLabFinal\\data\\01 pilot\\S1_data_clean.csv")
data
```

## 2. regression models
```{r}
model_1 <- brm(formula = response ~ category, family = "cumulative", data = data)
```
```{r}
model_2 <- brm(formula = response ~ category + pictureFormat, family = "cumulative", data = data)
```
```{r}
model_3 <- brm(formula = response ~ category + (category|pictureFormat), family = "cumulative", data = data)
```
```{r}
model_4 <- brm(formula = response ~ category + (1|experiment_id), family = "cumulative", data = data)
```
```{r}
model_5 <- brm(formula = response ~ category + pictureFormat + (1|experiment_id), family = "cumulative", data = data)
```
```{r}
model_6 <- brm(formula = response ~ category + (category|pictureFormat) + (1|experiment_id), family = "cumulative", data = data)
```
```{r}
model_1
model_2
model_3
model_4
model_5
model_6
```

##comparing the models to find the best
```{r}
loo1 <- loo(model_1)
loo2 <- loo(model_2)
loo3 <- loo(model_3)
loo4 <- loo(model_4)
loo5 <- loo(model_5)
loo6 <- loo(model_6)
```
```{r}
loo1
loo2
loo3
loo4
loo5
loo6
```
```{r}
loo_compare(loo1,loo2,loo3,loo4,loo5,loo6)
```

